### ISSUE TITLE
反馈个bug

### ISSUE THREAD

**Issue by Danehy** [Xposed-Modules-Repo/com.r.leapfebruary#13]
微信8043（28002b33）朋友圈广告去不了

![Screenshot_2024-01-03-23-11-31-933_com.tencent.mm-edit.jpg](https://github.com/Xposed-Modules-Repo/com.r.leapfebruary/assets/70059256/ae0650ff-0588-4e76-bf06-8da3cc3d995b)

**Comment by hsxazj** [comment]
我也失效了

**Comment by root0101010** [comment]
再试试
