### ISSUE TITLE
希望能调整聊天界面时间位置 上移一点

### ISSUE THREAD

**Issue by pope-L** [Xposed-Modules-Repo/com.r.leapfebruary#18]
希望能调整聊天界面时间位置 上移一点![Screenshot_2024-02-05-10-10-52-448_com.tencent.mm-edit.jpg](https://github.com/Xposed-Modules-Repo/com.r.leapfebruary/assets/32924101/af6ba75f-4f71-48c2-b9b9-7318ec756f14)

您看 
 那个时间与头像和名字有重叠

**Comment by root0101010** [comment]
再试一下

**Comment by pope-L** [comment]
抱歉这个时间打扰您，最新229 并没有发现 时间上移
还有所说红包是指什么功能呢似乎没见有提示

root0101010 ***@***.***> 于2024年2月8日周四 15:04写道：

**Comment by pope-L** [comment]
忘记说了 顺祝您 龙年身体健康 万事如意

PopeTemp(Gmail) ***@***.***> 于2024年2月9日周五 13:07写道：

**Comment by root0101010** [comment]
抢红包功能，装了就看到了
新年快乐
