### ISSUE TITLE
如何在beforeHookedMethod方法中打印被HOOK的应用信息（如包名、进程等）呢？

### ISSUE THREAD

**Issue by fangmomo123** [Xposed-Modules-Repo/com.r.leapfebruary#20]
使用了如lpparam.packageName、lpparam.processName等方法，打印出来的都是null、android等信息，并非hook的应用。
求大佬们解惑。
ps: 方法能正常hook。

**Comment by root0101010** [comment]
...这多看看Xposed的开发文档吧
