### ISSUE TITLE
WeChat 没有插件功能不能用😭😭

### ISSUE THREAD

**Issue by jacky-196** [Xposed-Modules-Repo/com.r.leapfebruary#21]
![Screenshot_2024-02-28-11-21-43-675_com tencent mm](https://github.com/Xposed-Modules-Repo/com.r.leapfebruary/assets/72303623/38c715df-d90a-4784-8c1d-1b51dabbf359)
尴尬

**Comment by root0101010** [comment]
版本不支持吧，换个版本看一下
