### ISSUE TITLE
反馈个bug

### ISSUE THREAD

**Issue by Hien123321** [Xposed-Modules-Repo/com.r.leapfebruary#3]
进去设置有几率会失效，点插件进去还是显示微信键盘的，而不是设置页面点多几次才是设置页面

**Comment by root0101010** [comment]
再试一下[2.2](https://github.com/Xposed-Modules-Repo/com.r.leapfebruary/releases/tag/22-2.2)

**Comment by Hien123321** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
