### ISSUE TITLE
模块功能页面空白

### ISSUE THREAD

**Issue by XZH2024** [Xposed-Modules-Repo/com.r.leapfebruary#40]
使用LSPosed启用模块并打开微信设置-插件，在加载了几秒钟后可以看到标题但是没有任何选项，模块版本2.38，微信版本为从releases下载的8.0.50，手机已root
我已经看过了常见问题
我尝试了重启手机，页面依然空白
运行过程中没有发现错误日志
我可以帮忙测试
![Screenshot_2024-08-31-20-50-09-830_com tencent mm](https://github.com/user-attachments/assets/72790dc2-aec8-4ca1-af3d-373758ba0c9c)

**Comment by XZH2024** [comment]
原来模块已经停更了，那只能这样了

**Comment by MarsMENGS** [comment]
请问是这个模块也没法用了是嘛
